export const FLAGS: Record<string, string> = {
  Amsterdam: "🇳🇱",
  Bangkok: "🇹🇭",
  Barcelona: "🇪🇸",
  Belgrade: "🇷🇸",
  Boom: "🇧🇪",
  Brussels: "🇧🇪",
  "Buenos Aires": "🇦🇷",
  Cannes: "🇫🇷",
  Cuzco: "🇵🇪",
  Geneva: "🇨🇭",
  Istanbul: "🇹🇷",
  Jasenice: "🇭🇷",
  Kyoto: "🇯🇵",
  "La Paz": "🇧🇴",
  Lisbon: "🇵🇹",
  Ljubljana: "🇸🇮",
  London: "🇬🇧",
  Lyon: "🇫🇷",
  "Machu Picchu": "🇵🇪",
  Madrid: "🇪🇸",
  "New Delhi": "🇮🇳",
  "New York": "🇺🇸",
  Ohrid: "🇲🇰",
  Paris: "🇫🇷",
  Prague: "🇨🇿",
  Rovinj: "🇭🇷",
  "San Martín de los Andes": "🇦🇷",
  Seoul: "🇰🇷",
  Shanghai: "🇨🇳",
  Taipei: "🇹🇼",
  Tbilisi: "🇬🇪",
  Tenerife: "🇪🇸",
  Tokyo: "🇯🇵",
  Uyuni: "🇧🇴",
  Verona: "🇮🇹",
};
