export interface JournalPost {
  slug: string;
  title: string;
  date: string;
  location: string;
  summary: string;
  body: string;
  photos?: string[];
  relatedTimeline?: string;
}

export const POSTS: JournalPost[] = [
  {
    slug: "shanghai-mu-2026",
    title: "MU Shanghai",
    date: "2026-05",
    location: "Shanghai",
    summary: `A month in Shanghai for muShanghai.`,
    body: `A month at [muShanghai](https://mushanghai.xyz/) — builders-only unconference in Minhang. Weekly themes: AI → Biotech → Robotics → Culture.

Direct in from Venice. Hi Cozy near the Bund. Quick detour to a festival in Beijing mid-month.

Exit is SH → NYC, straight into ETHGlobal.`,
    photos: [
      "/photos/shanghai-mu-2026/01.jpg",
      "/photos/shanghai-mu-2026/02.jpg",
      "/photos/shanghai-mu-2026/03.jpg",
      "/photos/shanghai-mu-2026/04.jpg",
      "/photos/shanghai-mu-2026/05.jpg",
      "/photos/shanghai-mu-2026/06.jpg",
      "/photos/shanghai-mu-2026/07.jpg",
      "/photos/shanghai-mu-2026/08.jpg",
      "/photos/shanghai-mu-2026/09.jpg",
      "/photos/shanghai-mu-2026/10.jpg",
      "/photos/shanghai-mu-2026/11.jpg",
      "/photos/shanghai-mu-2026/12.jpg",
    ],
  },
  {
    slug: "verona-2026",
    title: "Verona + Lake Garda",
    date: "2026-03",
    location: "Verona",
    summary: `Verona old city and Malcesine on Lake Garda.`,
    body: `Quick weekend: Giardino Giusti in Verona, then up Lake Garda to Malcesine, then down through Costermano.`,
    photos: [
      "/photos/verona-2026/01.jpg",
      "/photos/verona-2026/02.jpg",
      "/photos/verona-2026/03.jpg",
      "/photos/verona-2026/04.jpg",
      "/photos/verona-2026/05.jpg",
      "/photos/verona-2026/06.jpg",
      "/photos/verona-2026/07.jpg",
      "/photos/verona-2026/08.jpg",
      "/photos/verona-2026/09.jpg",
    ],
  },
  {
    slug: "spain-jan-2026",
    title: "Madrid → Valencia",
    date: "2026-01",
    location: "Madrid",
    summary: `Madrid, Valencia, and the canyons inland.`,
    body: `New Year's into Madrid, then south to Valencia. Day trip out to Los Calderones — the inland canyons that don't make it onto Valencia tourism pages.

Albufera at dusk.`,
    photos: [
      "/photos/spain-jan-2026/01.jpg",
      "/photos/spain-jan-2026/02.jpg",
      "/photos/spain-jan-2026/03.jpg",
      "/photos/spain-jan-2026/04.jpg",
      "/photos/spain-jan-2026/05.jpg",
      "/photos/spain-jan-2026/06.jpg",
      "/photos/spain-jan-2026/07.jpg",
      "/photos/spain-jan-2026/08.jpg",
      "/photos/spain-jan-2026/09.jpg",
      "/photos/spain-jan-2026/10.jpg",
      "/photos/spain-jan-2026/11.jpg",
    ],
  },
  {
    slug: "bolivia-2025",
    title: "Bolivia",
    date: "2025-12",
    location: "La Paz",
    summary: `La Paz, Potosí, and the salt flats of Uyuni.`,
    body: `Down from Peru into Bolivia. La Paz first (the altitude), then south to Potosí and Uyuni. Walking on the world's largest salt flat at sunrise was the cliché but it earned it.

Isla Incahuasi — cacti on what used to be the bottom of a prehistoric lake.`,
    photos: [
      "/photos/bolivia-2025/01.jpg",
      "/photos/bolivia-2025/02.jpg",
      "/photos/bolivia-2025/03.jpg",
      "/photos/bolivia-2025/04.jpg",
      "/photos/bolivia-2025/05.jpg",
      "/photos/bolivia-2025/06.jpg",
      "/photos/bolivia-2025/07.jpg",
      "/photos/bolivia-2025/08.jpg",
      "/photos/bolivia-2025/09.jpg",
      "/photos/bolivia-2025/10.jpg",
      "/photos/bolivia-2025/11.jpg",
      "/photos/bolivia-2025/12.jpg",
    ],
  },
  {
    slug: "peru-2025",
    title: "Peru",
    date: "2025-12",
    location: "Cuzco",
    summary: `Cuzco, the Sacred Valley, Machu Picchu.`,
    body: `Started in Cuzco, then up through the Sacred Valley — Chinchero, Temple of the Moon — and finally Machu Picchu. Then a few days in Mandor and the hot springs at Cocalmayo.

The altitude is real.`,
    photos: [
      "/photos/peru-2025/01.jpg",
      "/photos/peru-2025/02.jpg",
      "/photos/peru-2025/03.jpg",
      "/photos/peru-2025/04.jpg",
      "/photos/peru-2025/05.jpg",
      "/photos/peru-2025/06.jpg",
      "/photos/peru-2025/07.jpg",
      "/photos/peru-2025/08.jpg",
      "/photos/peru-2025/09.jpg",
      "/photos/peru-2025/10.jpg",
      "/photos/peru-2025/11.jpg",
    ],
  },
  {
    slug: "argentina-2025",
    title: "Argentina + Patagonia",
    date: "2025-11",
    location: "Buenos Aires",
    summary: `Three weeks in BA bookended by Patagonia.`,
    body: `Three weeks in Argentina — Buenos Aires steaks and Malbec, then south to Patagonia. San Martín de los Andes on Lago Lácar, mountain vistas around Nahuel Huapi.

Empanadas, parrillada, gelato breaks, Andean lakes at dusk.

Tagged on a hackathon (Closet at ETHGlobal Buenos Aires) but the trip was mostly Patagonia.`,
    photos: [
      "/photos/argentina-2025/01.jpg",
      "/photos/argentina-2025/02.jpg",
      "/photos/argentina-2025/03.jpg",
      "/photos/argentina-2025/04.jpg",
      "/photos/argentina-2025/05.jpg",
      "/photos/argentina-2025/06.jpg",
      "/photos/argentina-2025/07.jpg",
      "/photos/argentina-2025/08.jpg",
      "/photos/argentina-2025/09.jpg",
      "/photos/argentina-2025/10.jpg",
      "/photos/argentina-2025/11.jpg",
      "/photos/argentina-2025/12.jpg",
    ],
    relatedTimeline: "Closet",
  },
  {
    slug: "lyon-2025",
    title: "Lyon",
    date: "2025-10",
    location: "Lyon",
    summary: `Four days in Lyon for the music.`,
    body: `Four days in Lyon. Halle Tony Garnier for the show, Parc de la Tête d'Or for daylight, Vieux Lyon climb up to Fourvière for the in-between.`,
    photos: [
      "/photos/lyon-2025/01.jpg",
      "/photos/lyon-2025/02.jpg",
      "/photos/lyon-2025/03.jpg",
      "/photos/lyon-2025/04.jpg",
      "/photos/lyon-2025/05.jpg",
      "/photos/lyon-2025/06.jpg",
      "/photos/lyon-2025/07.jpg",
      "/photos/lyon-2025/08.jpg",
      "/photos/lyon-2025/09.jpg",
      "/photos/lyon-2025/10.jpg",
    ],
  },
  {
    slug: "tomorrowland-2025",
    title: "Tomorrowland",
    date: "2025-07",
    location: "Boom",
    summary: `Boom, Belgium. The festival.`,
    body: `De Schorre. Boom. The festival.`,
    photos: [
      "/photos/tomorrowland-2025/01.jpg",
      "/photos/tomorrowland-2025/02.jpg",
      "/photos/tomorrowland-2025/03.jpg",
      "/photos/tomorrowland-2025/04.jpg",
      "/photos/tomorrowland-2025/05.jpg",
      "/photos/tomorrowland-2025/06.jpg",
      "/photos/tomorrowland-2025/07.jpg",
      "/photos/tomorrowland-2025/08.jpg",
      "/photos/tomorrowland-2025/09.jpg",
      "/photos/tomorrowland-2025/10.jpg",
    ],
  },
  {
    slug: "amsterdam-may-2025",
    title: "Amsterdam",
    date: "2025-05",
    location: "Amsterdam",
    summary: `Five days in Amsterdam, non-hackathon edition.`,
    body: `Five days in Amsterdam, no hackathon this time. Vondelpark, Sloterpark, Meervaart, walking the canals.`,
    photos: [
      "/photos/amsterdam-may-2025/01.jpg",
      "/photos/amsterdam-may-2025/02.jpg",
      "/photos/amsterdam-may-2025/03.jpg",
      "/photos/amsterdam-may-2025/04.jpg",
      "/photos/amsterdam-may-2025/05.jpg",
      "/photos/amsterdam-may-2025/06.jpg",
      "/photos/amsterdam-may-2025/07.jpg",
      "/photos/amsterdam-may-2025/08.jpg",
      "/photos/amsterdam-may-2025/09.jpg",
      "/photos/amsterdam-may-2025/10.jpg",
    ],
  },
  {
    slug: "prague-may-2025",
    title: "Prague",
    date: "2025-05",
    location: "Prague",
    summary: `Five days in Prague, between hackathons.`,
    body: `Five days in Prague between events. Prague 1, Prague 4, Prague 7, Prague 10 — quieter version of the city.`,
    photos: [
      "/photos/prague-may-2025/01.jpg",
      "/photos/prague-may-2025/02.jpg",
      "/photos/prague-may-2025/03.jpg",
      "/photos/prague-may-2025/04.jpg",
      "/photos/prague-may-2025/05.jpg",
      "/photos/prague-may-2025/06.jpg",
      "/photos/prague-may-2025/07.jpg",
      "/photos/prague-may-2025/08.jpg",
      "/photos/prague-may-2025/09.jpg",
      "/photos/prague-may-2025/10.jpg",
    ],
  },
  {
    slug: "japan-2025",
    title: "Japan",
    date: "2025-04",
    location: "Tokyo",
    summary: `Two weeks across Honshu — Tokyo, Kyoto.`,
    body: `Two weeks across Honshu. Tokyo (Shibuya, Shimokita), then Kyoto for the temples and the maple-lined paths, then back through Tokyo. Long walking days, lots of trains, a lot of food. Kamogawa river by day and by night.

First time in Japan.`,
    photos: [
      "/photos/japan-2025/01.jpg",
      "/photos/japan-2025/02.jpg",
      "/photos/japan-2025/03.jpg",
      "/photos/japan-2025/04.jpg",
      "/photos/japan-2025/05.jpg",
      "/photos/japan-2025/06.jpg",
      "/photos/japan-2025/07.jpg",
      "/photos/japan-2025/08.jpg",
      "/photos/japan-2025/09.jpg",
      "/photos/japan-2025/10.jpg",
      "/photos/japan-2025/11.jpg",
      "/photos/japan-2025/12.jpg",
    ],
  },
  {
    slug: "tenerife-2025",
    title: "Tenerife",
    date: "2025-02",
    location: "Tenerife",
    summary: `Volcano, laurel forests, the rocks at Teno.`,
    body: `A week on Tenerife. Up Teide, through the laurel cloud forests of Teno, and out to the rocks where the island ends.

Different island than the one you see in tourism ads.`,
    photos: [
      "/photos/tenerife-2025/01.jpg",
      "/photos/tenerife-2025/02.jpg",
      "/photos/tenerife-2025/03.jpg",
      "/photos/tenerife-2025/04.jpg",
      "/photos/tenerife-2025/05.jpg",
      "/photos/tenerife-2025/06.jpg",
      "/photos/tenerife-2025/07.jpg",
      "/photos/tenerife-2025/08.jpg",
      "/photos/tenerife-2025/09.jpg",
    ],
  },
  {
    slug: "georgia-2025",
    title: "Tbilisi",
    date: "2025-02",
    location: "Tbilisi",
    summary: `Old town, Dry Bridge Market, sulfur baths.`,
    body: `Nine days in Tbilisi. The old town stairs, the Dry Bridge Market for Soviet camera lenses and silver, the sulfur baths in Abanotubani. Sameba Cathedral glowing across the Mtkvari at night.

Khinkali and Saperavi.`,
    photos: [
      "/photos/georgia-2025/01.jpg",
      "/photos/georgia-2025/02.jpg",
      "/photos/georgia-2025/03.jpg",
      "/photos/georgia-2025/04.jpg",
      "/photos/georgia-2025/05.jpg",
      "/photos/georgia-2025/06.jpg",
      "/photos/georgia-2025/07.jpg",
      "/photos/georgia-2025/08.jpg",
      "/photos/georgia-2025/09.jpg",
      "/photos/georgia-2025/10.jpg",
      "/photos/georgia-2025/11.jpg",
    ],
  },
  {
    slug: "paris-feb-2025",
    title: "Paris",
    date: "2025-02",
    location: "Paris",
    summary: `Six days in Paris in February.`,
    body: `Six days in Paris. République area, Place Franz Liszt, Saint-Vincent-de-Paul at night. The usual but slower because it was February and almost nobody was around.

Croissants, espresso, the boulevards empty.`,
    photos: [
      "/photos/paris-feb-2025/01.jpg",
      "/photos/paris-feb-2025/02.jpg",
      "/photos/paris-feb-2025/03.jpg",
      "/photos/paris-feb-2025/04.jpg",
      "/photos/paris-feb-2025/05.jpg",
      "/photos/paris-feb-2025/06.jpg",
      "/photos/paris-feb-2025/07.jpg",
      "/photos/paris-feb-2025/08.jpg",
      "/photos/paris-feb-2025/09.jpg",
      "/photos/paris-feb-2025/10.jpg",
    ],
  },
  {
    slug: "macedonia-2024",
    title: "Macedonia",
    date: "2024-08",
    location: "Ohrid",
    summary: `Ohrid and the Galichica National Park.`,
    body: `Almost two weeks in North Macedonia. Galichica National Park between two lakes, Matka Canyon, Ohrid old town and lakeside sunsets.`,
    photos: [
      "/photos/macedonia-2024/01.jpg",
      "/photos/macedonia-2024/02.jpg",
      "/photos/macedonia-2024/03.jpg",
      "/photos/macedonia-2024/04.jpg",
      "/photos/macedonia-2024/05.jpg",
      "/photos/macedonia-2024/06.jpg",
      "/photos/macedonia-2024/07.jpg",
      "/photos/macedonia-2024/08.jpg",
      "/photos/macedonia-2024/09.jpg",
      "/photos/macedonia-2024/10.jpg",
    ],
  },
  {
    slug: "croatia-aug-2024",
    title: "Croatia coast",
    date: "2024-08",
    location: "Rovinj",
    summary: `Otok Krk, Rab, Rovinj, Pag — island-hopping mid-August.`,
    body: `Long weekend doing the Croatian coast islands. Otok Krk, then Rab, then Rovinj, then Pag.`,
    photos: [
      "/photos/croatia-aug-2024/01.jpg",
      "/photos/croatia-aug-2024/02.jpg",
      "/photos/croatia-aug-2024/03.jpg",
      "/photos/croatia-aug-2024/04.jpg",
      "/photos/croatia-aug-2024/05.jpg",
      "/photos/croatia-aug-2024/06.jpg",
      "/photos/croatia-aug-2024/07.jpg",
      "/photos/croatia-aug-2024/08.jpg",
      "/photos/croatia-aug-2024/09.jpg",
      "/photos/croatia-aug-2024/10.jpg",
    ],
  },
  {
    slug: "croatia-jul-2024",
    title: "Dalmacija",
    date: "2024-07",
    location: "Jasenice",
    summary: `Down through Jasenice and the Dalmacija coast.`,
    body: `Down the coast through Jasenice and Brinje, into Dalmacija.`,
    photos: [
      "/photos/croatia-jul-2024/01.jpg",
      "/photos/croatia-jul-2024/02.jpg",
      "/photos/croatia-jul-2024/03.jpg",
      "/photos/croatia-jul-2024/04.jpg",
      "/photos/croatia-jul-2024/05.jpg",
      "/photos/croatia-jul-2024/06.jpg",
      "/photos/croatia-jul-2024/07.jpg",
      "/photos/croatia-jul-2024/08.jpg",
      "/photos/croatia-jul-2024/09.jpg",
      "/photos/croatia-jul-2024/10.jpg",
    ],
  },
];
