// Auto-generated by scripts/build-portrait.ts. Do not edit.
export const PORTRAIT = {
  src: "/portrait/avatar.jpg",
  webp200: "/portrait/avatar-200.webp",
  webp400: "/portrait/avatar-400.webp",
  width: 700,
  height: 700,
  blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoKAAoAA4BaJQBOgBuG5h6mUADiUBNK9If29aUQFKKBRkX239FGw3cour1AP7lEKt0zufiMDZHaMOvU2mK9Vdv0gEHTpf12ugGscAAA",
} as const;
