export interface Trip {
  slug: string;
  title: string;
  date: string;
  location: string;
  description: string;
  body?: string;
  photos?: string[];
  // Hackathon / project metadata (optional)
  project?: string;
  event?: string;
  prizes?: string;
  github?: string;
  showcase?: string;
  type?: "hackathon" | "project";
}

export const TRIPS: Trip[] = [
  {
    slug: "shanghai-mu-2026",
    title: "MU Shanghai",
    date: "2026-05",
    location: "Shanghai",
    description: `A month in Shanghai for muShanghai.`,
    event: "muShanghai",
    body: `A month at [muShanghai](https://mushanghai.xyz/) — builders-only unconference in Minhang. Weekly themes: AI → Biotech → Robotics → Culture.

Direct in from Venice. Hi Cozy near the Bund. Suzhou Creek mornings, Pudong skyline from the Bund, French Concession plane trees and e-scooter swarms, 1933 Shanghai (old abattoir) for the dark-fashion subculture. Sheng jian bao at Da Hu Chun. The Build hard. Sleep well. Have fun. Make friends. Don't burn out. MU manifesto.

Mid-month detour up to Beijing for a Great Wall festival.

Exit is SH → NYC, straight into ETHGlobal.`,
    photos: Array.from({ length: 31 }, (_, i) => `/photos/shanghai-mu-2026/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "verona-2026",
    title: "Verona + Lake Garda",
    date: "2026-03",
    location: "Verona",
    description: `Verona old city and Malcesine on Lake Garda.`,
    body: `Quick weekend: Giardino Giusti in Verona, then up Lake Garda to Malcesine, then down through Costermano.`,
    photos: [
      "/photos/verona-2026/01.jpg",
      "/photos/verona-2026/02.jpg",
      "/photos/verona-2026/03.jpg",
      "/photos/verona-2026/04.jpg",
      "/photos/verona-2026/05.jpg",
      "/photos/verona-2026/06.jpg",
      "/photos/verona-2026/07.jpg",
      "/photos/verona-2026/08.jpg",
      "/photos/verona-2026/09.jpg",
    ],
  },
  {
    slug: "cannes-2026",
    title: "Cannes",
    date: "2026-03",
    location: "Cannes",
    description: `Verified intelligence map for humans + AI agents`,
    body: `ETHGlobal Cannes 2026. Yachts at the Vieux Port, Belle Epoque corners at golden hour, the Carlton lit at night. Cursor stickers, ETHGlobal laptop stickers, Mediterranean view.`,
    photos: [
      "/photos/cannes-2026/01.jpg",
      "/photos/cannes-2026/02.jpg",
      "/photos/cannes-2026/03.jpg",
      "/photos/cannes-2026/04.jpg",
      "/photos/cannes-2026/05.jpg",
      "/photos/cannes-2026/06.jpg",
      "/photos/cannes-2026/07.jpg",
      "/photos/cannes-2026/08.jpg",
      "/photos/cannes-2026/09.jpg",
      "/photos/cannes-2026/10.jpg",
    ],
    project: "Ground Truth",
    event: "ETHGlobal Cannes",
    prizes: "World Agent Kit 2nd, ENS AI Agents 2nd",
    github: "https://github.com/grmkris/ethglobal-cannes-2026-groundtruth",
    showcase: "https://ethglobal.com/showcase/groundtruth-mz4us",
    type: "hackathon",
  },
  {
    slug: "spain-jan-2026",
    title: "Madrid → Valencia",
    date: "2026-01",
    location: "Madrid",
    description: `Madrid, Valencia, and the canyons inland.`,
    body: `New Year's into Madrid, then south to Valencia. Day trip out to Los Calderones — the inland canyons that don't make it onto Valencia tourism pages.

Albufera at dusk.`,
    photos: [
      "/photos/spain-jan-2026/01.jpg",
      "/photos/spain-jan-2026/02.jpg",
      "/photos/spain-jan-2026/03.jpg",
      "/photos/spain-jan-2026/04.jpg",
      "/photos/spain-jan-2026/05.jpg",
      "/photos/spain-jan-2026/06.jpg",
      "/photos/spain-jan-2026/07.jpg",
      "/photos/spain-jan-2026/08.jpg",
      "/photos/spain-jan-2026/09.jpg",
      "/photos/spain-jan-2026/10.jpg",
      "/photos/spain-jan-2026/11.jpg",
    ],
  },
  {
    slug: "uyuni-2025",
    title: "Salar de Uyuni",
    date: "2025-12",
    location: "Uyuni",
    description: `Potosí silver city → Salar de Uyuni night sky.`,
    body: `South Bolivia: Potosí first — the colonial silver-mining city, courtyards under rain — then the long drive down to the world's largest salt flat. Stars over the salar.`,
    photos: Array.from({ length: 6 }, (_, i) => `/photos/uyuni-2025/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "la-paz-2025",
    title: "La Paz",
    date: "2025-12",
    location: "La Paz",
    description: `Urban-altitude opening to the Bolivia leg.`,
    body: `La Paz at 3,640m. Witches' market corridors with hanging charms, Isabel la Católica statue lit between modern towers, the giant LA PAZ sign on the hillside at night. A themed bar with miniature whipala buses serving cocktails on the table.`,
    photos: Array.from({ length: 10 }, (_, i) => `/photos/la-paz-2025/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "machu-picchu-2025",
    title: "Machu Picchu",
    date: "2025-12",
    location: "Machu Picchu",
    description: `The pilgrimage moment of the Peru leg.`,
    body: `Train through the Sacred Valley to Aguas Calientes, then up to the citadel. Llamas on the terraces, the Intihuatana stone, the carved Royal Tomb cut directly into bedrock, the Temple of the Sun curve. Doorways framing Huayna Picchu like viewfinders.

Cloud-forest atmosphere most of the day. The bare tree on the terrace — quiet beat in the middle of the noise.`,
    photos: Array.from({ length: 25 }, (_, i) => `/photos/machu-picchu-2025/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "cuzco-2025",
    title: "Cuzco + Sacred Valley",
    date: "2025-12",
    location: "Cuzco",
    description: `Basecamp at altitude — Cuzco old town and the Sacred Valley.`,
    body: `Started in Cuzco — narrow Inca-stone alleys, Plaza de Armas — then up through the Sacred Valley: Chinchero, Temple of the Moon, Ollantaytambo. Then a few days at Mandor and the hot springs at Cocalmayo.

The altitude is real.`,
    photos: Array.from({ length: 10 }, (_, i) => `/photos/cuzco-2025/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "argentina-2025",
    title: "Buenos Aires",
    date: "2025-11",
    location: "Buenos Aires",
    description: `Devconnect week into ETHGlobal hackathon, capped with a Bombonera matchday.`,
    body: `Two weeks in Buenos Aires — Devconnect first (Nov 17–22), then straight into ETHGlobal BA where Closet took the Coinbase CDP track. La Boca and Caminito between sessions, the Maradona shrines, parrillada and gelato breaks, Jardín Japonés at golden hour.

Saturday at La Bombonera in full Boca kit. Puerto Madero at night to close the trip.`,
    photos: [
      "/photos/argentina-2025/01.jpg",
      "/photos/argentina-2025/02.jpg",
      "/photos/argentina-2025/03.jpg",
      "/photos/argentina-2025/04.jpg",
      "/photos/argentina-2025/05.jpg",
      "/photos/argentina-2025/06.jpg",
      "/photos/argentina-2025/07.jpg",
      "/photos/argentina-2025/08.jpg",
      "/photos/argentina-2025/09.jpg",
      "/photos/argentina-2025/10.jpg",
      "/photos/argentina-2025/11.jpg",
      "/photos/argentina-2025/12.jpg",
      "/photos/argentina-2025/13.jpg",
      "/photos/argentina-2025/14.jpg",
      "/photos/argentina-2025/15.jpg",
      "/photos/argentina-2025/16.jpg",
      "/photos/argentina-2025/17.jpg",
      "/photos/argentina-2025/18.jpg",
      "/photos/argentina-2025/19.jpg",
      "/photos/argentina-2025/20.jpg",
      "/photos/argentina-2025/21.jpg",
      "/photos/argentina-2025/22.jpg",
    ],
    project: "Closet",
    event: "Devconnect + ETHGlobal BA",
    prizes: "Coinbase CDP Winner",
    github: "https://github.com/grmkris/Closet---eth-global-Buenoes-Aires-2026",
    showcase: "https://ethglobal.com/showcase/closet-1fp8d",
    type: "hackathon",
  },
  {
    slug: "edge-city-patagonia-2025",
    title: "Edge City Patagonia",
    date: "2025-11",
    location: "San Martín de los Andes",
    description: `Edge City popup-city in the Andes — co-living, asados, alpine lakes.`,
    body: `Two weeks at Edge City Patagonia (Nov 2–14). Builders co-living in the foothills of the Andes — communal kitchen, the "I LIVE TO" sticky-note wall, long parrillada nights around the parrilla.

Days outside: Lanín National Park, Villa La Angostura, Los Arrayanes, the cloud-wrapped peaks above Nahuel Huapi. San Martín de los Andes town as basecamp. Stars over Patagonia at the end of the day.`,
    photos: [
      "/photos/edge-city-patagonia-2025/01.jpg",
      "/photos/edge-city-patagonia-2025/02.jpg",
      "/photos/edge-city-patagonia-2025/03.jpg",
      "/photos/edge-city-patagonia-2025/04.jpg",
      "/photos/edge-city-patagonia-2025/05.jpg",
      "/photos/edge-city-patagonia-2025/06.jpg",
      "/photos/edge-city-patagonia-2025/07.jpg",
      "/photos/edge-city-patagonia-2025/08.jpg",
      "/photos/edge-city-patagonia-2025/09.jpg",
      "/photos/edge-city-patagonia-2025/10.jpg",
      "/photos/edge-city-patagonia-2025/11.jpg",
      "/photos/edge-city-patagonia-2025/12.jpg",
      "/photos/edge-city-patagonia-2025/13.jpg",
      "/photos/edge-city-patagonia-2025/14.jpg",
      "/photos/edge-city-patagonia-2025/15.jpg",
      "/photos/edge-city-patagonia-2025/16.jpg",
    ],
    event: "Edge City",
  },
  {
    slug: "lyon-2025",
    title: "Lyon",
    date: "2025-10",
    location: "Lyon",
    description: `Four days in Lyon for Fred again..`,
    body: `Four days in Lyon for Fred again.. at Halle Tony Garnier. Parc de la Tête d'Or for daylight, Vieux Lyon climb up to Fourvière for the in-between.`,
    event: "Fred again..",
    photos: [
      "/photos/lyon-2025/01.jpg",
      "/photos/lyon-2025/02.jpg",
      "/photos/lyon-2025/03.jpg",
      "/photos/lyon-2025/04.jpg",
      "/photos/lyon-2025/05.jpg",
      "/photos/lyon-2025/06.jpg",
      "/photos/lyon-2025/07.jpg",
      "/photos/lyon-2025/08.jpg",
      "/photos/lyon-2025/09.jpg",
      "/photos/lyon-2025/10.jpg",
    ],
  },
  {
    slug: "geneva-2025",
    title: "Geneva",
    date: "2025-10",
    location: "Geneva",
    description: `Yosuke Yukimatsu at Palladium → drive home through the Alps.`,
    body: `Sat night at Palladium for Hellectronz — Yosuke Yukimatsu on the decks. Out at dawn, walked along the Rhone. Sunday in Geneva, Monday a slow drive home through Valais — Saint-Triphon, Sion, the vineyards above Brig, down through Gondo.`,
    photos: [
      "/photos/geneva-2025/01.jpg",
      "/photos/geneva-2025/02.jpg",
      "/photos/geneva-2025/03.jpg",
      "/photos/geneva-2025/04.jpg",
      "/photos/geneva-2025/05.jpg",
      "/photos/geneva-2025/06.jpg",
      "/photos/geneva-2025/07.jpg",
      "/photos/geneva-2025/08.jpg",
    ],
    event: "Yosuke Yukimatsu",
  },
  {
    slug: "new-delhi-2025",
    title: "New Delhi",
    date: "2025-09",
    location: "New Delhi",
    description: `Musician donation platform`,
    body: `ETHGlobal at Yashobhoomi. Butter chicken and thali, dhol drums and Mughal chandeliers at Khubani, a stray dog under tangled wires on the way home.`,
    photos: [
      "/photos/new-delhi-2025/01.jpg",
      "/photos/new-delhi-2025/02.jpg",
      "/photos/new-delhi-2025/03.jpg",
      "/photos/new-delhi-2025/04.jpg",
      "/photos/new-delhi-2025/05.jpg",
      "/photos/new-delhi-2025/06.jpg",
      "/photos/new-delhi-2025/07.jpg",
      "/photos/new-delhi-2025/08.jpg",
      "/photos/new-delhi-2025/09.jpg",
      "/photos/new-delhi-2025/10.jpg",
      "/photos/new-delhi-2025/11.jpg",
      "/photos/new-delhi-2025/12.jpg",
    ],
    project: "Opensource Orchestra",
    event: "ETHGlobal New Delhi",
    prizes: "ENS 1st Place",
    github: "https://github.com/grmkris/opensource-orchestra",
    showcase: "https://ethglobal.com/showcase/opensource-orchestra-y1egw",
    type: "hackathon",
  },
  {
    slug: "new-york-2025",
    title: "New York",
    date: "2025-08",
    location: "New York",
    description: `AI agents pay for APIs autonomously`,
    body: `ETHGlobal NY with 275 projects. Sabrett carts and yellow cabs, the skyline from Queens at night, Little Italy, Manhattanhenge down a street canyon.`,
    photos: [
      "/photos/new-york-2025/01.jpg",
      "/photos/new-york-2025/02.jpg",
      "/photos/new-york-2025/03.jpg",
      "/photos/new-york-2025/04.jpg",
      "/photos/new-york-2025/05.jpg",
      "/photos/new-york-2025/06.jpg",
      "/photos/new-york-2025/07.jpg",
      "/photos/new-york-2025/08.jpg",
      "/photos/new-york-2025/09.jpg",
      "/photos/new-york-2025/10.jpg",
      "/photos/new-york-2025/11.jpg",
      "/photos/new-york-2025/12.jpg",
    ],
    project: "AutoToll",
    event: "ETHGlobal New York",
    github: "https://github.com/grmkris/eth-global-new-york-2025-auto-toll",
    showcase: "https://ethglobal.com/showcase/autotoll-h7u9d",
    type: "hackathon",
  },
  {
    slug: "yoda-fun",
    title: "yoda.fun",
    date: "2025-08",
    location: "Ljubljana",
    description: `AI Oracle for prediction markets`,
    event: "Side Project",
    github: "https://yoda.fun",
    type: "project",
  },
  {
    slug: "tomorrowland-2025",
    title: "Tomorrowland",
    date: "2025-07",
    location: "Boom",
    description: `Boom, Belgium. The festival.`,
    body: `De Schorre. Boom. The festival.

Dreamville camping, the Art Nouveau pavilion with its glass-roof rotunda and pink waterfall curtain, the lake bridge lit purple at night, Avicii tribute on the screens. The Mainstage at golden hour with a Tomorrowland flag overhead. Industrial red-scaffolded stage at dusk. Stilt walkers, themed arches, the Great Library of Tomorrow.`,
    event: "Tomorrowland",
    photos: Array.from({ length: 36 }, (_, i) => `/photos/tomorrowland-2025/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "cannes-2025",
    title: "Cannes",
    date: "2025-07",
    location: "Cannes",
    description: `EIP-7702 hardware wallet sessions`,
    body: `ETHGlobal Cannes 2025. Bastille Day fireworks over the bay, two figures on Le Suquet's ancient ramparts under a peach gradient sky, the Palais des Festivals at blue hour, a full moon tracking along the Riviera. Apartment pasta cookups between the official sessions.`,
    photos: Array.from({ length: 12 }, (_, i) => `/photos/cannes-2025/${String(i + 1).padStart(2, "0")}.jpg`),
    project: "SessionFlow",
    event: "ETHGlobal Cannes",
    prizes: "Avail 2nd Place",
    github: "https://github.com/grmkris/eth-global-cannes-2025",
    showcase: "https://ethglobal.com/showcase/sessionflow-t4ok8",
    type: "hackathon",
  },
  {
    slug: "belgrade-2025",
    title: "Belgrade",
    date: "2025-06",
    location: "Belgrade",
    description: `Privacy-preserving universal AI access`,
    body: `ETH Belgrade. Skadarlija cobblestones, ćevapi, a Brutalist block at sunset, beer at Kalemegdan with the city lights below.`,
    photos: [
      "/photos/belgrade-2025/01.jpg",
      "/photos/belgrade-2025/02.jpg",
      "/photos/belgrade-2025/03.jpg",
      "/photos/belgrade-2025/04.jpg",
      "/photos/belgrade-2025/05.jpg",
      "/photos/belgrade-2025/06.jpg",
      "/photos/belgrade-2025/07.jpg",
      "/photos/belgrade-2025/08.jpg",
      "/photos/belgrade-2025/09.jpg",
      "/photos/belgrade-2025/10.jpg",
      "/photos/belgrade-2025/11.jpg",
    ],
    project: "Universal Basic AI",
    event: "ETH Belgrade",
    github: "https://github.com/grmkris/eth-belgrade-2025-universal-basic-ai",
    type: "hackathon",
  },
  {
    slug: "amsterdam-may-2025",
    title: "Amsterdam",
    date: "2025-05",
    location: "Amsterdam",
    description: `Five days in Amsterdam, non-hackathon edition.`,
    body: `Five days in Amsterdam, no hackathon this time. Vondelpark, Sloterpark, Meervaart, walking the canals.`,
    photos: [
      "/photos/amsterdam-may-2025/01.jpg",
      "/photos/amsterdam-may-2025/02.jpg",
      "/photos/amsterdam-may-2025/03.jpg",
      "/photos/amsterdam-may-2025/04.jpg",
      "/photos/amsterdam-may-2025/05.jpg",
      "/photos/amsterdam-may-2025/06.jpg",
      "/photos/amsterdam-may-2025/07.jpg",
      "/photos/amsterdam-may-2025/08.jpg",
      "/photos/amsterdam-may-2025/09.jpg",
      "/photos/amsterdam-may-2025/10.jpg",
    ],
  },
  {
    slug: "prague-may-2025",
    title: "Prague",
    date: "2025-05",
    location: "Prague",
    description: `ETHPrague + Mivio + the city.`,
    body: `Around ETHPrague: hacking in Prague 1, walks through Prague 4/7/10, the Vltava at dusk, vintage trams and the Powder Tower.`,
    photos: [
      "/photos/prague-may-2025/01.jpg",
      "/photos/prague-may-2025/02.jpg",
      "/photos/prague-may-2025/03.jpg",
      "/photos/prague-may-2025/04.jpg",
      "/photos/prague-may-2025/05.jpg",
      "/photos/prague-may-2025/06.jpg",
      "/photos/prague-may-2025/07.jpg",
      "/photos/prague-may-2025/08.jpg",
      "/photos/prague-may-2025/09.jpg",
      "/photos/prague-may-2025/10.jpg",
    ],
    project: "Mivio",
    event: "ETHGlobal Prague",
    prizes: "Yellow 1st Place",
    github: "https://github.com/grmkris/eth-global-prague-2025-mivio",
    showcase: "https://ethglobal.com/showcase/mivio-6ukub",
    type: "hackathon",
  },
  {
    slug: "kyoto-2025",
    title: "Kyoto",
    date: "2025-04",
    location: "Kyoto",
    description: `Temples, the Kamogawa, and the river crowds at night.`,
    body: `Middle leg of the Japan trip between two Tokyo stays. Gion lanterns at night, a red-lacquer shrine approach lined with stone lanterns, and the Kamogawa river — locals sitting equidistant along the bank in the spring evening.

First time in Japan.`,
    photos: Array.from({ length: 6 }, (_, i) => `/photos/kyoto-2025/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "tokyo-2025",
    title: "Tokyo",
    date: "2025-04",
    location: "Tokyo",
    description: `Konbini rituals, Shibuya neon, Bellwood nightcaps.`,
    body: `Tokyo as bookends of the Japan trip — first arrival and final exit. Konbini dairy aisles and 7-Eleven onigiri, izakaya storefronts with hand-chalked specials, the Yoshinoya beef bowl signs and the multi-floor bar directories lit at night. Meiji Shrine's torii under the zelkova canopy. Shibuya Sky after dark — the entire neon grid stretching to the horizon through glass. Late: yakiniku, then The Bellwood for cedar-tray nightcaps.

First time in Japan.`,
    photos: Array.from({ length: 22 }, (_, i) => `/photos/tokyo-2025/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "seoul-2025",
    title: "Seoul",
    date: "2025-04",
    location: "Seoul",
    description: `AI agent monetization platform`,
    body: `BuidlAI Seoul — middle leg of the Asia loop between ETHGlobal Taipei and Japan. Hongdae and Myeongdong nights, neon alleys, Lotte tower at dusk, Seokchon Lake cherry blossoms, Korean BBQ.

AgentForge took two 1st-place tracks (Nethermind + Rootstock) and a stage moment for NEAR AI.`,
    photos: [
      "/photos/seoul-2025/01.jpg",
      "/photos/seoul-2025/02.jpg",
      "/photos/seoul-2025/03.jpg",
      "/photos/seoul-2025/04.jpg",
      "/photos/seoul-2025/05.jpg",
      "/photos/seoul-2025/06.jpg",
      "/photos/seoul-2025/07.jpg",
      "/photos/seoul-2025/08.jpg",
      "/photos/seoul-2025/09.jpg",
      "/photos/seoul-2025/10.jpg",
      "/photos/seoul-2025/11.jpg",
    ],
    project: "AgentForge",
    event: "BuidlAI Seoul",
    prizes: "Nethermind 1st, Rootstock 1st",
    showcase: "https://devfolio.co/projects/agentforge-815e",
    type: "hackathon",
  },
  {
    slug: "taipei-2025",
    title: "Taipei",
    date: "2025-04",
    location: "Taipei",
    description: `AI adventure game with evolving NFTs`,
    body: `ETHGlobal Taipei. Neon streets and night markets, Songshan Ciyou temple with red lanterns at dusk, lu rou fan, Taipei 101 from Elephant Mountain.`,
    photos: [
      "/photos/taipei-2025/01.jpg",
      "/photos/taipei-2025/02.jpg",
      "/photos/taipei-2025/03.jpg",
      "/photos/taipei-2025/04.jpg",
      "/photos/taipei-2025/05.jpg",
      "/photos/taipei-2025/06.jpg",
      "/photos/taipei-2025/07.jpg",
      "/photos/taipei-2025/08.jpg",
      "/photos/taipei-2025/09.jpg",
      "/photos/taipei-2025/10.jpg",
      "/photos/taipei-2025/11.jpg",
      "/photos/taipei-2025/12.jpg",
    ],
    project: "Foreheads",
    event: "ETHGlobal Taipei",
    prizes: "Flow 2nd Place",
    github: "https://github.com/grmkris/eth-global-taipei-2025-forheads",
    showcase: "https://ethglobal.com/showcase/foreheads-3to1g",
    type: "hackathon",
  },
  {
    slug: "typeid-drizzle-zod-example",
    title: "typeid-drizzle-zod-example",
    date: "2025-04",
    location: "Ljubljana",
    description: `Type-safe TypeIDs with Drizzle ORM and Zod validation`,
    event: "Open Source",
    github: "https://github.com/grmkris/typeid-drizzle-zod-example",
    type: "project",
  },
  {
    slug: "tenerife-2025",
    title: "Tenerife",
    date: "2025-02",
    location: "Tenerife",
    description: `Volcano, laurel forests, the rocks at Teno.`,
    body: `A week on Tenerife. Up Teide, through the laurel cloud forests of Teno, and out to the rocks where the island ends.

Different island than the one you see in tourism ads.`,
    photos: [
      "/photos/tenerife-2025/01.jpg",
      "/photos/tenerife-2025/02.jpg",
      "/photos/tenerife-2025/03.jpg",
      "/photos/tenerife-2025/04.jpg",
      "/photos/tenerife-2025/05.jpg",
      "/photos/tenerife-2025/06.jpg",
      "/photos/tenerife-2025/07.jpg",
      "/photos/tenerife-2025/08.jpg",
      "/photos/tenerife-2025/09.jpg",
    ],
  },
  {
    slug: "georgia-2025",
    title: "Tbilisi",
    date: "2025-02",
    location: "Tbilisi",
    description: `Old town, Dry Bridge Market, sulfur baths.`,
    body: `Nine days in Tbilisi. The old town stairs, the Dry Bridge Market for Soviet camera lenses and silver, the sulfur baths in Abanotubani. Sameba Cathedral glowing across the Mtkvari at night.

Khinkali and Saperavi.`,
    photos: [
      "/photos/georgia-2025/01.jpg",
      "/photos/georgia-2025/02.jpg",
      "/photos/georgia-2025/03.jpg",
      "/photos/georgia-2025/04.jpg",
      "/photos/georgia-2025/05.jpg",
      "/photos/georgia-2025/06.jpg",
      "/photos/georgia-2025/07.jpg",
      "/photos/georgia-2025/08.jpg",
      "/photos/georgia-2025/09.jpg",
      "/photos/georgia-2025/10.jpg",
      "/photos/georgia-2025/11.jpg",
    ],
  },
  {
    slug: "paris-feb-2025",
    title: "Paris",
    date: "2025-02",
    location: "Paris",
    description: `Six days in Paris in February.`,
    body: `Six days in Paris. République area, Place Franz Liszt, Saint-Vincent-de-Paul at night. The usual but slower because it was February and almost nobody was around.

Croissants, espresso, the boulevards empty.`,
    photos: [
      "/photos/paris-feb-2025/01.jpg",
      "/photos/paris-feb-2025/02.jpg",
      "/photos/paris-feb-2025/03.jpg",
      "/photos/paris-feb-2025/04.jpg",
      "/photos/paris-feb-2025/05.jpg",
      "/photos/paris-feb-2025/06.jpg",
      "/photos/paris-feb-2025/07.jpg",
      "/photos/paris-feb-2025/08.jpg",
      "/photos/paris-feb-2025/09.jpg",
      "/photos/paris-feb-2025/10.jpg",
    ],
  },
  {
    slug: "bangkok-2024",
    title: "Bangkok",
    date: "2024-11",
    location: "Bangkok",
    description: `Cross-chain swaps via Circle CCTP`,
    body: `ETHGlobal Bangkok. Tuk-tuks at night, street-food vendors, Thai red curry, neon malls, EM Wonder Bangkok.`,
    photos: [
      "/photos/bangkok-2024/01.jpg",
      "/photos/bangkok-2024/02.jpg",
      "/photos/bangkok-2024/03.jpg",
      "/photos/bangkok-2024/04.jpg",
      "/photos/bangkok-2024/05.jpg",
      "/photos/bangkok-2024/06.jpg",
      "/photos/bangkok-2024/07.jpg",
      "/photos/bangkok-2024/08.jpg",
      "/photos/bangkok-2024/09.jpg",
      "/photos/bangkok-2024/10.jpg",
    ],
    project: "AruSwap",
    event: "ETHGlobal Bangkok",
    prizes: "CoW DAO 2nd, World Pool Prize",
    github: "https://github.com/Lucianosc/aru-swap",
    showcase: "https://ethglobal.com/showcase/aruswap-ebpfr",
    type: "hackathon",
  },
  {
    slug: "macedonia-2024",
    title: "Macedonia",
    date: "2024-08",
    location: "Ohrid",
    description: `Ohrid, Galichica, Matka Canyon, an outdoor wedding.`,
    body: `Almost two weeks in North Macedonia. Galichica National Park between two lakes — bubble-tent glamping at Grizzly Igloo. Matka Canyon dam tunnel and gorge. Ohrid old town and lakeside sunsets — castle hill lit against the dusk. Mixed-meze boards, Temjanika wine, kajmak crisps. An outdoor wedding with sparkler cake.`,
    photos: Array.from({ length: 19 }, (_, i) => `/photos/macedonia-2024/${String(i + 1).padStart(2, "0")}.jpg`),
  },
  {
    slug: "croatia-aug-2024",
    title: "Croatia coast",
    date: "2024-08",
    location: "Rovinj",
    description: `Otok Krk, Rab, Rovinj, Pag — island-hopping mid-August.`,
    body: `Long weekend doing the Croatian coast islands. Otok Krk, then Rab, then Rovinj, then Pag.`,
    photos: [
      "/photos/croatia-aug-2024/01.jpg",
      "/photos/croatia-aug-2024/02.jpg",
      "/photos/croatia-aug-2024/03.jpg",
      "/photos/croatia-aug-2024/04.jpg",
      "/photos/croatia-aug-2024/05.jpg",
      "/photos/croatia-aug-2024/06.jpg",
      "/photos/croatia-aug-2024/07.jpg",
      "/photos/croatia-aug-2024/08.jpg",
      "/photos/croatia-aug-2024/09.jpg",
      "/photos/croatia-aug-2024/10.jpg",
    ],
  },
  {
    slug: "croatia-jul-2024",
    title: "Dalmacija",
    date: "2024-07",
    location: "Jasenice",
    description: `Down through Jasenice and the Dalmacija coast.`,
    body: `Down the coast through Jasenice and Brinje, into Dalmacija.`,
    photos: [
      "/photos/croatia-jul-2024/01.jpg",
      "/photos/croatia-jul-2024/02.jpg",
      "/photos/croatia-jul-2024/03.jpg",
      "/photos/croatia-jul-2024/04.jpg",
      "/photos/croatia-jul-2024/05.jpg",
      "/photos/croatia-jul-2024/06.jpg",
      "/photos/croatia-jul-2024/07.jpg",
      "/photos/croatia-jul-2024/08.jpg",
      "/photos/croatia-jul-2024/09.jpg",
      "/photos/croatia-jul-2024/10.jpg",
    ],
  },
  {
    slug: "brussels-2024",
    title: "Brussels",
    date: "2024-07",
    location: "Brussels",
    description: `On-chain Tic-Tac-Toe with prize pools`,
    body: `ETHGlobal Brussels. Aerial approach, hackathon under skylights, Grimbergen on a terrace, Grand-Place beer, Mont des Arts at golden hour, Stella on the flight home.`,
    photos: [
      "/photos/brussels-2024/01.jpg",
      "/photos/brussels-2024/02.jpg",
      "/photos/brussels-2024/03.jpg",
      "/photos/brussels-2024/04.jpg",
      "/photos/brussels-2024/05.jpg",
      "/photos/brussels-2024/06.jpg",
      "/photos/brussels-2024/07.jpg",
      "/photos/brussels-2024/08.jpg",
      "/photos/brussels-2024/09.jpg",
      "/photos/brussels-2024/10.jpg",
    ],
    project: "TicTac4Ever",
    event: "ETHGlobal Brussels",
    prizes: "NounsDAO 3rd, Worldcoin Pool",
    github: "https://github.com/grmkris/eth-brussels-2024",
    showcase: "https://ethglobal.com/showcase/tictac4ever-09zcr",
    type: "hackathon",
  },
  {
    slug: "prague-2024-06",
    title: "Prague",
    date: "2024-06",
    location: "Prague",
    description: `Meme voting platform with charitable contributions`,
    body: `ETHPrague. Old Town Municipal House at night, rooftop aperol + laptop, the Žižkov TV tower across the city, Troja bridge over the Vltava.`,
    photos: [
      "/photos/prague-2024-06/01.jpg",
      "/photos/prague-2024-06/02.jpg",
      "/photos/prague-2024-06/03.jpg",
      "/photos/prague-2024-06/04.jpg",
      "/photos/prague-2024-06/05.jpg",
      "/photos/prague-2024-06/06.jpg",
      "/photos/prague-2024-06/07.jpg",
      "/photos/prague-2024-06/08.jpg",
      "/photos/prague-2024-06/09.jpg",
      "/photos/prague-2024-06/10.jpg",
    ],
    project: "Degens for Future",
    event: "ETHPrague",
    prizes: "2nd Place",
    github: "https://github.com/grmkris/eth-prague-2024",
    showcase: "https://devfolio.co/projects/degens-for-future-fd7e",
    type: "hackathon",
  },
  {
    slug: "london-2024",
    title: "London",
    date: "2024-03",
    location: "London",
    description: `Social sports betting platform`,
    project: "BuddyBet",
    event: "ETHGlobal London",
    prizes: "Chiliz Pool, Arbitrum Pool",
    github: "https://github.com/grmkris/eth-london-2024",
    showcase: "https://ethglobal.com/showcase/buddybet-tmhp4",
    type: "hackathon",
  },
  {
    slug: "drizzle-pg-notify-audit-table",
    title: "drizzle-pg-notify-audit-table",
    date: "2024-01",
    location: "Ljubljana",
    description: `PostgreSQL real-time audit tables with Drizzle ORM`,
    event: "Open Source",
    github: "https://github.com/grmkris/drizzle-pg-notify-audit-table",
    type: "project",
  },
  {
    slug: "istanbul-2023",
    title: "Istanbul",
    date: "2023-11",
    location: "Istanbul",
    description: `Web3 payment processing with auto-conversion`,
    project: "LoomPay",
    event: "ETHGlobal Istanbul",
    prizes: "Unlimit 2nd, Safe 4th",
    github: "https://github.com/grmkris/eth-global-istanbul",
    showcase: "https://ethglobal.com/showcase/loompay-8p0us",
    type: "hackathon",
  },
  {
    slug: "paris-2023",
    title: "Paris",
    date: "2023-07",
    location: "Paris",
    description: `Privacy-focused ZK identity wallet`,
    project: "PEERwallet",
    event: "ETHGlobal Paris",
    prizes: "Polygon ID 1st, Biconomy Pool",
    github: "https://github.com/seddik11/peer-wallet",
    showcase: "https://ethglobal.com/showcase/peerwallet-do6c6",
    type: "hackathon",
  },
  {
    slug: "barcelona-2023",
    title: "Barcelona",
    date: "2023-07",
    location: "Barcelona",
    description: `Private voting system`,
    project: "PeerVote",
    event: "ETHBarcelona",
    prizes: "Best Public Goods",
    showcase: "https://devfolio.co/projects/peervote-5c90",
    type: "hackathon",
  },
  {
    slug: "prague-2023",
    title: "Prague",
    date: "2023-06",
    location: "Prague",
    description: `P2P resource sharing network`,
    project: "PeerUp",
    event: "ETHPrague",
    prizes: "5 prizes",
    showcase: "https://devfolio.co/projects/peer-up-e096",
    type: "hackathon",
  },
  {
    slug: "lisbon-2023",
    title: "Lisbon",
    date: "2023-05",
    location: "Lisbon",
    description: `Web2/Web3 credential verification`,
    project: "checkmarks.io",
    event: "ETHGlobal Lisbon",
    prizes: "Polygon ID 3rd, The Graph Pool",
    github: "https://github.com/grmkris/checkmarks.io",
    showcase: "https://ethglobal.com/showcase/checkmarks-io-ugznb",
    type: "hackathon",
  },
  {
    slug: "amsterdam-2022",
    title: "Amsterdam",
    date: "2022-04",
    location: "Amsterdam",
    description: `Dapp discovery and showcase platform`,
    project: "Web3Hunt",
    event: "ETHAmsterdam",
    prizes: "Optimism Deploy, The Graph 1st",
    github: "https://github.com/web3hunt/web3hunt",
    showcase: "https://ethglobal.com/showcase/web3hunt-43443",
    type: "hackathon",
  },
];
