#!/usr/bin/env bun
/**
 * Generate variants + blur for the avatar portrait at public/portrait/avatar.jpg.
 *
 * Outputs:
 *   public/portrait/avatar-200.webp   1x at 96px target (2x density)
 *   public/portrait/avatar-400.webp   2x for retina
 *   src/content/portrait.generated.ts   blur dataURL + dimensions
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";

const SRC = "public/portrait/avatar.jpg";
const OUT_DIR = "public/portrait";
const META_OUT = "src/content/portrait.generated.ts";
const WIDTHS = [200, 400] as const;
const QUALITY = 85;

// Square face crop. Source is 1500x2000 portrait with face in upper third.
// Crop a 700x700 window centered on face_y≈575, image center x=750.
const CROP = { left: 400, top: 200, width: 700, height: 700 } as const;

async function main() {
  const meta = await sharp(SRC).metadata();
  if (!meta.width || !meta.height) throw new Error("no dimensions");

  // Pre-crop pipeline: extract face-centered square, then downsize per variant.
  const cropped = sharp(SRC).extract(CROP);
  const croppedBuffer = await cropped.toBuffer();

  for (const width of WIDTHS) {
    await sharp(croppedBuffer)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: QUALITY })
      .toFile(join(OUT_DIR, `avatar-${width}.webp`));
  }

  const blurBuffer = await sharp(croppedBuffer)
    .resize({ width: 10 })
    .webp({ quality: 40 })
    .toBuffer();
  const blur = `data:image/webp;base64,${blurBuffer.toString("base64")}`;

  const ts = `// Auto-generated by scripts/build-portrait.ts. Do not edit.
export const PORTRAIT = {
  src: "/portrait/avatar.jpg",
  webp200: "/portrait/avatar-200.webp",
  webp400: "/portrait/avatar-400.webp",
  width: ${CROP.width},
  height: ${CROP.height},
  blur: "${blur}",
} as const;
`;
  await writeFile(META_OUT, ts);
  console.log(`✓ wrote ${META_OUT}`);
  console.log(`  ${meta.width}x${meta.height}, blur ${blurBuffer.length}B`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
